### ISSUE TITLE
Compilation Error in Caché 2017.2

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/RESTForms#28]
Possibly #22 related.

While compiling classes from `master` branch, I get this-like error messages:

```
ОШИБКА #5373: Класс '%Library.Object', используемый 'Form.Generators:onGenerateMetadata:FormalSpec', не существует
```

...and so on. Seem like deprecated `%Object` wasn't replaced to `%DynamicObject`.

**Comment by ZitRos** [comment]
Ah, I see. There are a lot of system methods left.

**Comment by eduard93** [comment]
[Releases](https://github.com/intersystems-ru/RESTForms/releases) are provided for 2016.1 and 2016.2+. 
The conversion is done automatically using [SMR}(https://github.com/intersystems-ru/SystemMethodsRemover)

**Comment by eduard93** [comment]
Since it's much easier to do 16.1 -> 16.2 automatic conversion rather than 16.2->16.1 there are currently no particular plans to move the RESTForms codebase into 16.2,

**Comment by ZitRos** [comment]
I haven't found any description of steps how to set it up (in readme).
Could you please provide one? (Instead of just "import classes")

**Comment by eduard93** [comment]
How to set what up? SMR? Importing classes is enough.

**Comment by ZitRos** [comment]
How to set up RESTForms for Caché 2017+. Importing classes gives the error
above.

**Comment by eduard93** [comment]
Import [release](https://github.com/intersystems-ru/RESTForms/releases) for 2016.2+

**Comment by ZitRos** [comment]
Got it. Maybe consider adding this to readme (could just be a link to releases page)? I was thinking that you still use some utilities like "repository import to Caché", so managed to import master branch directly instead of releases, just like it says: `Import classes and create web app with Form.REST.Main broker.`

**Comment by eduard93** [comment]
Sure. Done.

**Comment by ZitRos** [comment]
Thanks!
