### ISSUE TITLE
Update record doesn't work

### ISSUE THREAD

**Issue by schoenmakers** [intersystems-ru/RESTForms#32]
When I am using this code and i am trying to update a record it doesn't work... Create, Read and Delete seem to work well...  see attached screencast
![screencast-172 17 19 81-57772-2019 01 09-10-20-03](https://user-images.githubusercontent.com/2921751/50889707-ee291e00-13f8-11e9-96cf-fa7a99bcdf9a.gif)

**Comment by eduard93** [comment]
Hello!

Fixed with the [new release](https://github.com/intersystems-ru/RESTForms/releases/download/v1.6.1/Form162.xml)

**Comment by schoenmakers** [comment]
Works like a charm !!! great thanks
